### ISSUE TITLE
'Frameworks/TTLock.framework/TTLock' does not contain bitcode

### ISSUE THREAD

**Issue by ahmedalttai** [ttlock/iOS_SDK_Demo#5]
Hello,

when i upload the watchOS app that contains the TTLock framework to the appstore it gives me this error:
ITMS-90496: Invalid Executable - The executable '/Watch/mm.app/PlugIns/mm Extension.appex/Frameworks/TTLock.framework/TTLock' does not contain bitcode.

ITMS-90496: Invalid Executable - The executable 'mm.app/Watch/mm.app/PlugIns/mm Extension.appex/mm Extension' does not contain bitcode.

**Comment by JuannyiOS** [comment]
Hello,
Due to the limit of GitHub reply size，i have sent the new version sdk to your email.Please check it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ttlock/iOS_SDK_Demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月11日(星期五) 晚上9:14
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ttlock/iOS_SDK_Demo] 'Frameworks/TTLock.framework/TTLock' does not contain bitcode (#5)





 
Hello,
 
when i upload the watchOS app that contains the TTLock framework to the appstore it gives me this error:
 ITMS-90496: Invalid Executable - The executable '/Watch/mm.app/PlugIns/mm Extension.appex/Frameworks/TTLock.framework/TTLock' does not contain bitcode.
 
ITMS-90496: Invalid Executable - The executable 'mm.app/Watch/mm.app/PlugIns/mm Extension.appex/mm Extension' does not contain bitcode.

**Comment by ahmedalttai** [comment]
Thank you it worked.
