### ISSUE TITLE
CoreBluetooth is not correctly initialized

### ISSUE THREAD

**Issue by BrunoRV** [ttlock/iOS_SDK_Demo#8]
Hello.

We're trying to integrate your framework into our Swift project. We've followed your documentation, but still haven't found a fix for a problem we're having.

The initialization of the bluetooth fails. It logs

`TTLockLog#####scan，CoreBluetooth is not correctly initialized !#####`

And the TTLock scan doesn't work at all. We're able to communicate with the lock having the lockData, but we're unable to scan it.

The app asks for bluetooth permission and we've accepted the prompt at the device, but this error still appears.

Any advice on how to make the TTLock bluetooth work? I've set up a [demo project](https://github.com/BrunoRV/TTLockTest) to show you what we're trying to do so you can see the error first hand.

Thanks in advance.

**Comment by JuannyiOS** [comment]
Thank you for your feedback.
We will make the tint better or other methods to make&nbsp;integrate&nbsp;easier.


only set up is success, other functions can use normal

&nbsp;TTLock.setupBluetooth { state in&nbsp; &nbsp;
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if state == TTBluetoothState.poweredOn {
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; TTLock.startScan({ a in
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; print(a.debugDescription)
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; })
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
 
&nbsp; &nbsp; &nbsp; &nbsp; }





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ttlock/iOS_SDK_Demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月20日(星期五) 凌晨0:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ttlock/iOS_SDK_Demo] CoreBluetooth is not correctly initialized (#8)





 
Hello.
 
We're trying to integrate your framework into our Swift project. We've followed your documentation, but still haven't found a fix for a problem we're having.
 
The initialization of the bluetooth fails. It logs
 
TTLockLog#####scan，CoreBluetooth is not correctly initialized !#####
 
And the TTLock scan doesn't work at all. We're able to communicate with the lock having the lockData, but we're unable to scan it.
 
The app asks for bluetooth permission and we've accepted the prompt at the device, but this error still appears.
 
Any advice on how to make the TTLock bluetooth work? I've set up a demo project to show you what we're trying to do so you can see the error first hand.
 
Thanks in advance.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BrunoRV** [comment]
Thank you for your response. It's working now.
